---
- name: Helps  to download file
  hosts: localhost
  become: yes
  become_method: sudo
  vars_prompt:
    - name: destination
      prompt: "Give locations: "
      private: no
  tasks:
    - name: Download 1 package
      get_url:
        url: "{{destination}}"
        dest: /tmp/
