---
- name: Install r1soft-agent
  hosts: target
  become: yes
  become_method: sudo
  tasks:
    - name: Create Repository
      block:
        copy:
          src: r1soft.repo
          dest: /etc/yum.repo.d/r1soft

      - name: Install r1soft-agent
        package:
          name: serverbackup-enterprise-agent
          state: latest

      - name: Start Engine
        systemd:
          name: sbm-agent
          state: restarted

      - name: Get key
        shell: "r1soft-setup --get-key https://r1soft.acirrustech.com"
        when: ansible_facts['distribution'] == 'CentOS' and ansible_distribution_major_version == "7"



############## CENTOS 6 ##############

    - name: Create Repository
      block:
        copy:
          src: r1soft.repo
          dest: /etc/yum.repo.d/r1soft

      - name: Install r1soft-agent
        package:
          name: serverbackup-enterprise-agent
          state: latest

      - name: Start Engine
        service:
          name: cdp-agent
          state: restarted

      - name: Get key
        shell: "r1soft-setup --get-key https://r1soft.acirrustech.com"
        when: ansible_facts['distribution'] == 'CentOS' and ansible_distribution_major_version == "6"
